### ISSUE TITLE
TypeError: e.getSettings is not a function. (In 'e.getSettings()', 'e.getSettings' is undefined

### ISSUE THREAD

**Issue by Unixon-solutions** [ConnectyCube/connectycube-js-sdk-releases#21]
I am getting this error when trying to call getUserMedia on IOS in case of video conference call
In android there is no such issue.

Please let me know what's the fix for this issue

**Comment by DaveLomber** [comment]
@Unixon-solutions thanks for reporting 

is it about iOS Safari browser or iOS Cordova web view?

**Comment by Unixon-solutions** [comment]
Its IOS WKWebView

**Comment by DaveLomber** [comment]
Thanks

so this about Cordova iOS RTC plugin 

and where 'getSettings' is still in todo
https://github.com/cordova-rtc/cordova-plugin-iosrtc/blob/master/docs/iosrtc.md#iosrtcmediastreamtrack

Anyway, 
we found 2 places where we use  'getSettings'

One of them is for logging purpose only, which we just removed safely 

Another one is inside 'getUserMedia' which we are discussing internally what to do with it 

Will keep you posted

**Comment by DaveLomber** [comment]
@Unixon-solutions the issue is fixed
the new release will be pushed during next couple days max

**Comment by Unixon-solutions** [comment]
RemoteStreamListener was not triggering on iOS in case of video conference call.
will that work in new release ?

**Comment by DaveLomber** [comment]
@Unixon-solutions we have released 3.0.3 version 
Could you please upgrade and let us know whether the issue is resolved or not

**Comment by Unixon-solutions** [comment]
Still getting same error for iOS
And there is a bug in 3.0.3 called "delete e.elementId;" then used e.elementId in attachMediaStream
![Screenshot 2020-05-05 at 4 46 58 PM](https://user-images.githubusercontent.com/47319424/81060434-12fbab80-8ef0-11ea-8da9-760a91dc1205.png)

**Comment by DaveLomber** [comment]
could you please let us know where exactly you commented these lines

**Comment by Unixon-solutions** [comment]
key: "getUserMedia", inside this function

**Comment by DaveLomber** [comment]
You also can try 3.0.4

Here we have the following code:

`    const trackSetting = (!track.getSettings || Utils.getEnv().reactnative) ? null : track.getSettings()`

so if `getSettings` is not available then it should not be called

**Comment by Unixon-solutions** [comment]
3.0.4 is not working
Not getting error but still not getting device media
Please check in iOS

**Comment by DaveLomber** [comment]
Please try 3 0 6 
it should work well  - I just checked it

**Comment by Unixon-solutions** [comment]
I have tried 3.0.6
It worked when I commented this line "delete e.elementId;"

And still onRemoteStreamListener is not triggering in iOS

**Comment by DaveLomber** [comment]
We are checking re 'onRemoteStreamListener'
Will update soon

**Comment by DaveLomber** [comment]
A link to 'onRemoteStreamListener' issue root cause https://github.com/cordova-rtc/cordova-plugin-iosrtc/issues/505

**Comment by DaveLomber** [comment]
@Unixon-solutions please apply this solution https://github.com/cordova-rtc/cordova-plugin-iosrtc/issues/505#issuecomment-626132977

It should fix the  'onRemoteStreamListener' issue.

**Comment by Unixon-solutions** [comment]
Should I just use  https://webrtchacks.github.io/adapter/adapter-latest.js 
or I need to modify it ?

**Comment by DaveLomber** [comment]
Just put the mentioned code after `iosrtc.registerGlobals();`

**Comment by Unixon-solutions** [comment]
Can you please send me updated JS ?

**Comment by DaveLomber** [comment]
@Unixon-solutions please try this sample https://github.com/ConnectyCube/connectycube-cordova-samples/tree/master/sample-videochat-conf-cordova

both getSettings and on remote stream are fixed 

the only one issue we still face is that on iOS the streams are displayed behind body el 

To fix it - Need to call `iosrtc.refreshVideos()` at some place 

We are working on it

**Comment by hthetiot** [comment]
We going to handle missing getSetilting here https://github.com/cordova-rtc/cordova-plugin-iosrtc/issues/482

Note if you have to call `iosrtc.refreshVideos()` it might be you doing something out of order because the plug-in should trigger it on DOM change automatically. Feel free to fill an issue if you can.

**Comment by Unixon-solutions** [comment]
`applyShimOnTrack();` worked for iOS.
